version: "3.8"

services:
  # mongo database
  mongo:
    container_name: mongoDB
    build: ./mongo
    networks:
      network1:
        ipv4_address: 10.10.10.3

  # ftp server
  ftp_server:
    container_name: ftp_server
    build: ./ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS= "one|1234"
    networks:
      network1:
        ipv4_address: 10.10.10.2


  # go api
  api_server:
    container_name: api_server
    build: ./src/api
    ports:
      - target: 8080
        published: 8080
        protocol: tcp

    networks:
      hostnetwork:
        ipv4_address: 20.20.20.4
      network1:
        ipv4_address: 10.10.10.4

volumes:
  # mongodb persistant storage
  mongodb-data:
  

networks:
  # this is for the api to communicate with the outside world
  hostnetwork:
    internal: false
    ipam:
      config: 
        - subnet: 20.20.20.0/24
  
  # this is for the api to communicate with the internal services
  network1:
    internal: true
    ipam:
      config: 
        - subnet: 10.10.10.0/24
