version: "3.8"

services:
  mongo:
    container_name: mongoDB
    build: ./mongo
    networks:
      - network1

  ftpd_server:
    container_name: pure-ftpd
    build: ./ftp
    networks:
      - network1
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/username

volumes:
  mongodb-data:
  

networks:
  network1:
    internal: true
    ipam:
      config: 
        - subnet: 10.10.10.0/24
