version: "3.8"

services:
  mongo:
    container_name: mongoDB
    build: ./mongo
    networks:
      network1:
        ipv4_address: 10.10.10.3

  ftpd_server:
    container_name: pure-ftpd
    build: ./ftp
    networks:
      network1:
        ipv4_address: 10.10.10.2

    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/username

  api_server:
    container_name: api_server
    build: ./src/api
    ports:
      - target: 8080
        published: 8080
        protocol: tcp

    networks:
      hostnetwork:
        ipv4_address: 20.20.20.4
      network1:
        ipv4_address: 10.10.10.4

volumes:
  mongodb-data:
  

networks:
  # this is for the api to communicate with the outside world
  hostnetwork:
    internal: false
    ipam:
      config: 
        - subnet: 20.20.20.0/24
  
  # this is for the api to communicate with the internal services
  network1:
    internal: true
    ipam:
      config: 
        - subnet: 10.10.10.0/24
