# base info
openapi: 3.0.3
info:
  version: 1.0.0
  title: CooPIR API
  description: The Coordinated Platform for Incident Response API.

# server information
servers:
  - url: http://localhost:8080/api/v1
    description: "localhost development server"
    variables:
      port:
        default: "8080"
      basePath:
        default: "/api/v1"


# security features (the api uses a JWT token that is received through a login)


# paths
paths:
  /ping:
    get:
      summary: "Ping the API"
      description: "Returns a simple message to confirm the API is up and running"
      operationId: "ping"
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: string
                description: "pong"
  /file:
    get:
      description: Returns a file
      operationId: getFile
      parameters:
        - name: filename
          in: query
          description: The file to return
          required: true
          schema:
            type: string
        - name: casename
          in: query
          description: The name of the case
          required: true
          schema:
            type: string
      responses:
        200:
          description: File
          content:
            application/octet-stream:
              schema:
                type: object
                format: binary
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The error message
        404:
          description: File not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The error message
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: internal server error
    post:
      description: Uploads a file
      operationId: uploadFile
      parameters:
        - name: file
          in: query
          description: The file to upload
          required: true
          schema:
            type: string
        - name: filename
          in: query
          description: The filename specified by the user
          required: true
          schema:
            type: string
        - name: casename
          in: query
          description: The case to upload the file to
          required: true
          schema:
            type: string
      responses:
        200:
          description: File uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
    delete:
      description: Deletes a file
      operationId: deleteFile
      parameters:
        - name: filename
          in: query
          description: The file to delete
          required: true
          schema:
            type: string
      responses:
        200:
          description: File deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /db/test:
    get:
      description: test
      responses:
        '200':
          description: Successful response
    post:
      description: test
      responses:
        '200':
          description: Successful response
  /db/test/find:
    get:
      description: test
      responses:
        '200':
          description: Successful response
    post:
      description: test
      responses:
        '200':
          description: Successful response
  /login:
    post:
      description: Login
      operationId: login
      parameters:
        - name: username
          in: query
          description: The username
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password
          required: true
          schema:
            type: string
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The JWT token
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /auth/logout:
    post:
      description: Logout
      operationId: logout
      parameters:
        - name: token
          in: query
          description: The JWT token
          required: true
          schema:
            type: string
      responses:
        200:
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /auth/renew:
    post:
      description: Renew token
      operationId: renew
      parameters:
        - name: token
          in: query
          description: The JWT token
          required: true
          schema:
            type: string
      responses:
        200:
          description: Renew successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The JWT token
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /case:
    get: 
      description: returns all case metadata
      parameters:
        - name: json_request
          in: query
          description: JSON request for cases
          required: true
          schema:
            type: string
      responses:
        200:
          description: Operation Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: the success message
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Internal Server Error                    
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Case not found
  /cases: 
    get:
      description: Get all cases the user can see
      parameters:
        - name: json_request
          in: query
          description: request to get all cases
          required: true
          schema:
            type: string
      responses:
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Internal Server Error
        200:
          description: Operation Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: list of all cases
  /case/make: 
    get:
      description: returns true if the user can edit or make cases
      parameters:
        - name: uuid
          in: query
          description: uuid of user
          required: true
          schema:
            type: string
      responses:
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Internal Server Error
        200:
          description: Operation Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Operation Successful  
  /case/files: 
    get:
      description: returns all files in case
      parameters:
        - name: caseUUID
          in: query
          description: request to get all cases
          required: true
          schema:
            type: string
      responses:
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Internal Server Error
        200:
          description: Operation Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Operation Successful
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Bad Request
        404:
          description: Not Found
          content: 
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Not Found
  /case/new:
    post:
      description: Creates a new case
      parameters:
        - name: json_request
          in: query
          description: request to create new case
          required: true
          schema:
            type: string
      responses:
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: string
                    description: Case already exists
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Internal Server Error
        200:
          description: Operation Successful
          content:
            application/json:
              schema: 
                type: object
                properties:
                  error:
                    type: string
                    description: Successful Creation of Case
  /case/update:
    post:
      description: Updates the selected case
      parameters:
        - name: json_request
          in: query
          description: request to update case
          required: true
          schema:
            type: string
      responses:
        200:
          description: Operation Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Successful Update of Case
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Internal Server Error
  /user:
    get:
      description: returns all user metadata
      parameters:
        - name: json_request
          in: query
          description: request for user info
          required: true
          schema:
            type: string
      responses:
        200:
          description: Operation Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: successful query of user info
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Internal Server Error
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: User Not Found
  /user/new:
    post:
      description: creates new user
      parameters:
        - name: json_request
          in: query
          description: request to make new user
          required: true
          schema:
            type: string
      responses:
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Internal Server Error
  /user/edit:
    get:
      description: returns true if user can edit
      parameters:
        - name: uuid
          in: query
          description: checks the uuid of user
          required: true
          schema:
            type: string
      responses:
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Internal Server Error      
        200:
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Successful Operation
  /user/update:
    post:
      description: updates user info
      parameters:
        - name: json_request
          in: query
          description: updates user info
          required: true
          schema:
            type: string
      responses:
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Internal Server Error 
  /file/info:
    get:
      description: returns file metadata
      parameters:
        - name: json_request
          in: query
          description: returns file metadata
          required: true
          schema:
            type: string
      responses:
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Internal Server Error
        200: 
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Successful Operation