basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  title: CooPIR API
  version: 1.0.0
paths:
  /file:
    get:
      description: get file from seaweedfs
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: get file from seaweedfs
      tags:
      - Files
swagger: "2.0"
